### ISSUE TITLE
Unable to use

### ISSUE THREAD

**Issue by tylergannon** [sirbrillig/gitnews-menubar#113]
![Screen Shot 2021-07-20 at 9 28 56 AM](https://user-images.githubusercontent.com/50593/126361155-7ca31410-1dc8-4102-b165-4f56f90dc0db.png)

I created a token with the desired privileges.

Revoking now and will check later back to see if this project is being updated.
thanks!

**Comment by sirbrillig** [comment]
Wow, I haven't seen that error before! Let me see if I can figure out what it's talking about.

**Comment by sirbrillig** [comment]
What version of the Mac OS are you using?

**Comment by tylergannon** [comment]
Fully up to date, late-2017 intel-based MBP

![Screen Shot 2021-07-20 at 11 41 36 AM](https://user-images.githubusercontent.com/50593/126378065-3fb90635-85de-4d73-a5ef-ff99c08cf0f1.png)

**Comment by sirbrillig** [comment]
This is tricky. Some research into that error seems to imply that it _might_ be caused by an issue with node-fetch in some versions of node. Of course, this app is all packaged up so I'm not sure how that could happen. It'd be nice to see the full stack trace but something seems to have changed recently that makes it so that opening the debug console in the production app doesn't work. 😞 

I assume you've tried this more than once? I've seen weird errors from time to time when the app starts, but restarting seems to fix them.

If you can reproduce this reliably, and you're willing and interested to help, we could try downloading [the source](https://github.com/sirbrillig/gitnews-menubar/archive/refs/tags/v1.7.0.zip) to your machine, then running `yarn && yarn start` in the uncompressed directory (you'll need [yarn](https://yarnpkg.com/)). Then you should be able to see the full stack trace of the error either in the terminal itself, or in the app's devtools window (which should already be open but if not you can press CMD-SHIFT-c when the app is visible). 

If you don't feel like going through all that effort, I totally understand, and we might be able to find someone else who has your issue that can reproduce it. Or maybe I can add in some code to log the error message in a place that we can more easily find it. 🤔  Anecdotally I know quite a few folks (myself included) who are using it just fine so there must be something different happening here.

**Comment by tylergannon** [comment]
Hey thanks for taking your time to give a detailed response.  Which node version should I be using?  I guess I'll use `16.5.0` based on your `.circleci` config.

Sure thing I'll start it up locally and see if it still errors, or else get you a stack trace.

**Comment by sirbrillig** [comment]
This should be resolved (hopefully) by version 2.0 which uses octokit instead of node-fetch.
